sudo: required
services:
- docker
language: go
go:
- 1.5.4
- 1.6.2
env:
  global:
    - SNAP_PLUGIN_SOURCE=/home/travis/gopath/src/github.com/intelsdi-x/snap-plugin-publisher-heka
    - HEKA_SOURCE=/home/travis/gopath/src/github.com/mozilla-services/heka
  matrix:
    - TEST=unit
    - TEST=integration
# NOTE: addons required for Heka:
addons:
  apt:
    packages:
      - protobuf-compiler
      - cmake
      - libgeoip-dev
before_install:
- go get github.com/tools/godep
- if [ ! -d $SNAP_PLUGIN_SOURCE ]; then mkdir -p $HOME/gopath/src/github.com/intelsdi-x; ln -s $TRAVIS_BUILD_DIR $SNAP_PLUGIN_SOURCE; fi # CI for forks not from intelsdi-x
- mkdir -p /home/travis/gopath/src/github.com/mozilla-services
- cd /home/travis/gopath/src/github.com/mozilla-services
- git clone http://github.com/mozilla-services/heka || true
install:
- export TMPDIR=$HOME/tmp
- mkdir -p $TMPDIR
- cd $HEKA_SOURCE
- source ./build.sh
- cd $SNAP_PLUGIN_SOURCE # change dir into source
- export GOPATH=$HEKA_SOURCE/build/heka:$GOPATH
- make deps

script:
- make check TEST=$TEST 2>&1 # Run test suite
notifications:
  slack:
    secure: VkbZLIc2RH8yf3PtIAxUNPdAu3rQQ7yQx0GcK124JhbEnZGaHyK615V0rbG7HcVmYKGPdB0cXqZiLBDKGqGKb2zR1NepOe1nF03jxGSpPq8jIFeEXSJGEYGL34ScDzZZGuG6qwbjFcXiW5lqn6t8igzp7v2+URYBaZo5ktCS2xY=
